<a href="https://colab.research.google.com/github/Bharat-Kulkarni/COT6610-ML/blob/master/Assignment4_3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
import urllib.request
urllib.request.urlretrieve ("http://qwone.com/~jason/20Newsgroups/20news-bydate-matlab.tgz", "temp.tar.gz")
import tarfile
tar = tarfile.open("temp.tar.gz")
tar.extractall()
tar.close()

In [8]:
dataset = np.loadtxt("20news-bydate/matlab/train.data", delimiter=" ", dtype = int)
print(len(dataset))
print(dataset)

1467345
[[    1     1     4]
 [    1     2     2]
 [    1     3    10]
 ...
 [11269 48919     1]
 [11269 51544     1]
 [11269 53958     1]]


In [0]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
X = TfidfTransformer()


In [0]:
phi_T = X.fit_transform(dataset)
#

In [12]:
 print(phi_T.shape[0])
 print(phi_T)

1467345
  (0, 2)	0.9428090415820635
  (0, 1)	0.23570226039551587
  (0, 0)	0.23570226039551587
  (1, 2)	0.6666666666666666
  (1, 1)	0.6666666666666666
  (1, 0)	0.3333333333333333
  (2, 2)	0.9534625892455924
  (2, 1)	0.28603877677367767
  (2, 0)	0.09534625892455924
  (3, 2)	0.6963106238227914
  (3, 1)	0.6963106238227914
  (3, 0)	0.17407765595569785
  (4, 2)	0.3651483716701107
  (4, 1)	0.9128709291752769
  (4, 0)	0.18257418583505536
  (5, 2)	0.16222142113076254
  (5, 1)	0.9733285267845753
  (5, 0)	0.16222142113076254
  (6, 2)	0.14002800840280097
  (6, 1)	0.9801960588196068
  (6, 0)	0.14002800840280097
  (7, 2)	0.12309149097933272
  (7, 1)	0.9847319278346618
  (7, 0)	0.12309149097933272
  (8, 2)	0.3144854510165755
  :	:
  (1467336, 0)	0.3720793969152829
  (1467337, 2)	3.287283452384545e-05
  (1467337, 1)	0.9288548123057769
  (1467337, 0)	0.3704439722492143
  (1467338, 2)	3.156563099543453e-05
  (1467338, 1)	0.9345952025128257
  (1467338, 0)	0.3557130956875518
  (1467339, 2)	3.1040290352838

In [0]:
x_t= np.array(phi_T)

x = x.transpose() #phi

In [21]:
numRows = len(dataset)
k = 2
theta = np.random.randn(numRows, k)
print(len(theta))# theta.size[1])
print(theta)


1467345
[[ 1.15060343 -1.2769465 ]
 [-0.00990217  2.46901779]
 [ 0.06586346  0.73646044]
 ...
 [ 0.33445444 -0.16430231]
 [-0.98401201 -0.23202352]
 [-0.58289727 -0.97354899]]


In [0]:
# prod = np.matmul(x_t,x)   

ValueError: ignored

In [0]:
while(true):
  theta_new = np.matmul(prod,theta)  # Step1
  theta_new = np.linalg.qr(theta_new)

  factor = np.linalg.norm(theta_new - theta)
  if(factor < 0.1):   #Near convergance 
    break;
  